import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@/public/styles/global.css";
import Providers from "./Providers";
import SideBar from "@/app/sidebar/sidebar";
import Box from "@mui/material/Box";
import { store } from "@/redux/store";
import {Montserrat} from "next/font/google";
import localFont from "next/font/local";

const montserrat = Montserrat({ subsets: ["latin"] });

const myFont = localFont({
  src: "../public/fonts/BeautifulPeoplePersonalUse-dE0g.ttf",
  weight: "400", 
  style: "normal", 
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getUser() {
  return true; // or false if not logged in
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getUser();

  return (
    <html lang="en">
      <body className={`antialiased ${montserrat.className}`}>
        <Providers>
          {user ? (
            <Box sx={{ display: "flex" }}>
              <SideBar className={myFont.className}>
                 {children}
              </SideBar>
            </Box>
          ) : (
            // <main style={{ padding: "24px" }}>{children}</main>
            ""
          )}
        </Providers>
      </body>
    </html>
  );
}
