import "./globals.css";
// import "../public/styles/globals.css";
import Providers from "./Providers";
import {Montserrat} from "next/font/google";
import localFont from "next/font/local";
import { getServerSession } from "next-auth";
import { authOptions } from "../lib/authOptions";
import SidebarWrapper from "./sidebar/sidebarWrapper";
const montserrat = Montserrat({ subsets: ["latin"] });

const myFont = localFont({
  src: "../public/fonts/BeautifulPeoplePersonalUse-dE0g.ttf",
  weight: "400", 
  style: "normal", 
});


// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

async function getUser() {
  return true; // or false if not logged in
}

export default async function RootLayout({children}) {
  
  const session = await getServerSession(authOptions);
  console.log("session",session);
  return (
    <html lang="en">
      <body className={`antialiased ${montserrat.className}`}>
        <Providers>
          <SidebarWrapper>{children}</SidebarWrapper>
        </Providers>
      </body>
    </html>
  );
}
